// Package model holds the domain types shared across the gateway's layers.
package model

import "time"

// User is a registered account in the gateway.
//
// ID is a UUID (generated by google/uuid). Email is the unique login
// identifier. PasswordHash stores the bcrypt hash of the password — the
// plaintext password is never kept in memory. CreatedAt is the registration
// timestamp.
type User struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
